version: '3.3'

services:
  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:v2.1.1
    restart: always
    ports:
      - "8080:8080"
    environment:
      - AUTHENTICATION_API_KEY=g3st@03Du4rd0
      - DATABASE_PROVIDER=mysql
      - DATABASE_CONNECTION_URI=mysql://u540193243_frpe:g3st@03Du4rd0@mysql:3306/u540193243_frpe_crm_db
      - DATABASE_CLIENT_NAME=evolution_exchange
      # Configuração do Redis (Novo!)
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://redis:6379/0
      - CACHE_REDIS_PREFIX=evolution
    depends_on:
      - mysql
      - redis

  mysql:
    container_name: evolution_mysql
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=g3st@03Du4rd0
      - MYSQL_DATABASE=u540193243_frpe_crm_db
      - MYSQL_USER=u540193243_frpe
      - MYSQL_PASSWORD=g3st@03Du4rd0
    ports:
      - "3307:3306"
    volumes:
      - evolution_mysql:/var/lib/mysql

  # Serviço Redis (Novo!)
  redis:
    container_name: evolution_redis
    image: redis:alpine
    restart: always # Comando forçando IPv4 e proteção desativada para rede interna
    command: redis-server --appendonly yes --bind 0.0.0.0 --protected-mode no
    volumes:
      - evolution_redis:/data

volumes:
  evolution_mysql:
  evolution_redis:
